/* Generated by uv-core codegen */

'use client';

import { useCurrentRowSync } from '@/components/core/hooks/useStoreHooks';
import { TextInput, DateInputField, NumberInput, BooleanInput } from '@/components/core/page/fields';
import type { UVUsers } from '@/lib/common/ds/types/app/UVUsers.js';
import type { Store } from 'uv-core/client';

export default function UVUsersEditForm({ store }: { store: Store<UVUsers> }) {
  const row = useCurrentRowSync(store);
  if (!row || !store) {
    return null;
  }
  return (
    <div className="grid gap-4 py-4">
      <TextInput store={store} attributeCode="displayName" label="Display Name" />
      <TextInput store={store} attributeCode="email" label="Email" />
      <TextInput store={store} attributeCode="userName" label="User Name" />
      <TextInput store={store} attributeCode="apiKey" label="Api Key" />
      <TextInput store={store} attributeCode="locationName" label="Location Name" />
      <TextInput store={store} attributeCode="ipAddress" label="Ip Address" />
      <DateInputField store={store} attributeCode="startDate" label="Start Date" />
      <DateInputField store={store} attributeCode="endDate" label="End Date" />
      <DateInputField store={store} attributeCode="lastLogin" label="Last Login" />
      <DateInputField store={store} attributeCode="lastFailedLogin" label="Last Failed Login" />
      <DateInputField store={store} attributeCode="lastPasswordReset" label="Last Password Reset" />
      <NumberInput store={store} attributeCode="failedLoginAttempts" label="Failed Login Attempts" />
      <NumberInput store={store} attributeCode="userId" label="User Id" />
      <BooleanInput store={store} attributeCode="locked" label="Locked" />
    </div>
  );
}
