/* Generated by uv-core codegen */

'use client';

import { useCurrentRowSync } from '@/components/core/hooks/useStoreHooks';
import { DateInputField, TextInput } from '@/components/core/page/fields';
import type { UVRoles } from '@/lib/common/ds/types/app/UVRoles.js';
import type { StoreClass as Store } from 'uv-core/client';

export default function UVRolesEditForm({ store }: { store: Store<UVRoles> }) {
  const row = useCurrentRowSync(store);
  if (!row || !store) {
    return null;
  }
  return (
    <div className="grid gap-4 py-4">
      <TextInput store={store} attributeCode="appId" label="App Id" />
      <TextInput store={store} attributeCode="description" label="Description" />
      <DateInputField store={store} attributeCode="endDate" label="End Date" />
      <TextInput store={store} attributeCode="roleCode" label="Role Code" />
      <TextInput store={store} attributeCode="roleName" label="Role Name" />
      <DateInputField store={store} attributeCode="startDate" label="Start Date" />
    </div>
  );
}
