/* Generated by uv-core codegen */

import { UVUsersDS } from './UVUsersDS.js';

import { UVRolesDS } from './UVRolesDS.js';
export const APP_DATASOURCES = {
  UVRoles: UVRolesDS,
  UVUsers: UVUsersDS,
};
