/* Generated by uv-core codegen */

import { UVUsersDS } from './UVUsersDS';
import { UVRolesDS } from './UVRolesDS';
import { SavedSearchDS } from './SavedSearchDS';

export const APP_DATASOURCES = {
  UVRoles: UVRolesDS,
  UVUsers: UVUsersDS,
  SavedSearch: SavedSearchDS,
};
