/* Generated by uv-core codegen */

import type { TableDataSource } from 'uv-core';
import { DefaultAttribute, DefaultDataSource, DefaultFullAccess } from 'uv-core';
import type { UVRoles } from '../../../common/ds/types/app/UVRoles.js';

export const UVRolesDS: TableDataSource<UVRoles> = {
  ...DefaultDataSource,
  id: 'UVRoles',
  schema: 'sm',
  tableName: 'uv_roles',
  attributes: [
    {
      ...DefaultAttribute,
      code: 'appId',
      name: 'App Id',
      type: 'Text',
      column: 'app_id',
      maxLength: 128,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'createdAt',
      name: 'Created At',
      type: 'Date',
      column: 'created_at',
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'createdBy',
      name: 'Created By',
      type: 'Text',
      column: 'created_by',
      maxLength: 128,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'description',
      name: 'Description',
      type: 'Text',
      column: 'description',
    },
    {
      ...DefaultAttribute,
      code: 'endDate',
      name: 'End Date',
      type: 'Date',
      column: 'end_date',
    },
    {
      ...DefaultAttribute,
      code: 'roleCode',
      name: 'Role Code',
      type: 'Text',
      column: 'role_code',
      maxLength: 128,
      primary: true,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'roleName',
      name: 'Role Name',
      type: 'Text',
      column: 'role_name',
      maxLength: 128,
      primary: true,
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'startDate',
      name: 'Start Date',
      type: 'Date',
      column: 'start_date',
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'updatedAt',
      name: 'Updated At',
      type: 'Date',
      column: 'updated_at',
      optional: false,
    },
    {
      ...DefaultAttribute,
      code: 'updatedBy',
      name: 'Updated By',
      type: 'Text',
      column: 'updated_by',
      maxLength: 128,
      optional: false,
    }
  ],
  access: [
    {
      ...DefaultFullAccess,
      roleCode: 'admin',
    },
    {
      ...DefaultFullAccess,
      roleCode: 'all_users',
    },
  ],
};
