/* Generated by uv-core codegen */

'use client';

import type { Column } from '@/components/core/smart-search/types';
import { useClientSession } from '@/components/core/session-context';
import type { UVUsers } from '@/lib/common/ds/types/app/UVUsers.js';
import { useMemo } from 'react';

export default function useUVUsersSmartSearchColumns(): Column<UVUsers>[] {
  const session = useClientSession();
  const roles = session?.roles;
  return useMemo(() => {
    if (!roles) {
      return [];
    }
    const columns: Column<UVUsers>[] = [
      {
        key: 'apiKey',
        label: 'Api Key',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'createdAt',
        label: 'Created At',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'createdBy',
        label: 'Created By',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'displayName',
        label: 'Display Name',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'email',
        label: 'Email',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'endDate',
        label: 'End Date',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'failedLoginAttempts',
        label: 'Failed Login Attempts',
        type: 'Number',
        defaultOperator: 'eq',
      },
      {
        key: 'ipAddress',
        label: 'Ip Address',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'lastFailedLogin',
        label: 'Last Failed Login',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'lastLogin',
        label: 'Last Login',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'locationName',
        label: 'Location Name',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'locked',
        label: 'Locked',
        type: 'Boolean',
        defaultOperator: 'istrue',
      },
      {
        key: 'startDate',
        label: 'Start Date',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'userName',
        label: 'User Name',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'userId',
        label: 'User Id',
        type: 'Number',
        defaultOperator: 'eq',
      },
    ];
    return columns;
  }, [roles]);
}
