/* Generated by uv-core codegen */

'use client';

import type { Column } from '@/components/core/smart-search/types';
import { useClientSession } from '@/components/core/session-context';
import type { UVRoles } from '@/lib/common/ds/types/app/UVRoles.js';
import { useMemo } from 'react';

export default function useUVRolesSmartSearchColumns(): Column<UVRoles>[] {
  const session = useClientSession();
  const roles = session?.roles;
  return useMemo(() => {
    if (!roles) {
      return [];
    }
    const columns: Column<UVRoles>[] = [
      {
        key: 'appId',
        label: 'App Id',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'createdAt',
        label: 'Created At',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'createdBy',
        label: 'Created By',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'endDate',
        label: 'End Date',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'roleCode',
        label: 'Role Code',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'roleName',
        label: 'Role Name',
        type: 'Text',
        defaultOperator: 'is',
      },
      {
        key: 'startDate',
        label: 'Start Date',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'updatedAt',
        label: 'Updated At',
        type: 'Date',
        defaultOperator: 'on',
      },
      {
        key: 'updatedBy',
        label: 'Updated By',
        type: 'Text',
        defaultOperator: 'is',
      },
    ];
    return columns;
  }, [roles]);
}
