/* Generated by uv-core codegen */

'use client';

import { PageLayoutTemplate } from '@/components/core/page';
import { ShoppingCart } from 'lucide-react';
import UVRolesEditForm from './components/edit-form';
import useUVRolesSmartSearchColumns from './hooks/smart-search-columns';
import useUVRolesTableColumns from './hooks/table-columns';
import { useUVRolesStore } from './hooks/use-store';

export default function UVRolesPageContent() {
  const store = useUVRolesStore();
  const smartSearchColumns = useUVRolesSmartSearchColumns();
  const tableColumns = useUVRolesTableColumns(store);

  return (
      <PageLayoutTemplate
        title="Uvroles"
        subTitle="Manage Uvroles"
        icon={<ShoppingCart className="h-12 w-12 text-muted-foreground" />}
        store={store}
        smartSearchColumns={smartSearchColumns}
        tableColumns={tableColumns}
        pageId="uvroles-page"
        itemId="uvroles"
        editForm={<UVRolesEditForm store={store} />}
        getDefaultRow={() => {
          return {};
        }}
        addNewButtonText="Add New Uvroles"
      />
    );
  }
