/* Generated by uv-core codegen */

'use client';

import * as React from 'react';
import type { UVUsersStore } from '../lib/client/hooks/useUVUsersStore.js';
import type { UVUsers } from '../lib/common/ds/types/UVUsers.js';

interface UVUsersFormProps {
  store: UVUsersStore;
  rowId: string;
}

export function UVUsersForm({ store, rowId }: UVUsersFormProps) {
  const row = store.row(rowId);
  if (!row) {
    return <div className="p-4 text-sm text-slate-400">Record not found</div>;
  }

  return (
    <div className="space-y-4 p-4 bg-slate-900/50 rounded-lg border border-slate-800">
      <h3 className="text-sm font-medium text-slate-200">
        {row._status === 'I' ? 'New Record' : `Edit: ${rowId}`}
      </h3>
      <div className="space-y-4">
        <div className="flex flex-col gap-1">
          <label htmlFor="apiKey" className="text-xs font-semibold text-slate-400">
            Api Key
          </label>
          <input
            id="apiKey"
            type="text"
            value={row['apiKey'] ?? ''}
            onChange={(e) => store.setValue('apiKey', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={256}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="apiSecret" className="text-xs font-semibold text-slate-400">
            Api Secret
          </label>
          <input
            id="apiSecret"
            type="text"
            value={row['apiSecret'] ?? ''}
            onChange={(e) => store.setValue('apiSecret', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={256}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="createdAt" className="text-xs font-semibold text-slate-400">
            Created At *
          </label>
          <input
            id="createdAt"
            type="datetime-local"
            value={row['createdAt'] ? String(row['createdAt']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('createdAt', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="createdBy" className="text-xs font-semibold text-slate-400">
            Created By *
          </label>
          <input
            id="createdBy"
            type="text"
            value={row['createdBy'] ?? ''}
            onChange={(e) => store.setValue('createdBy', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="displayName" className="text-xs font-semibold text-slate-400">
            Display Name *
          </label>
          <input
            id="displayName"
            type="text"
            value={row['displayName'] ?? ''}
            onChange={(e) => store.setValue('displayName', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="endDate" className="text-xs font-semibold text-slate-400">
            End Date
          </label>
          <input
            id="endDate"
            type="datetime-local"
            value={row['endDate'] ? String(row['endDate']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('endDate', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="failedLoginAttempts" className="text-xs font-semibold text-slate-400">
            Failed Login Attempts *
          </label>
          <input
            id="failedLoginAttempts"
            type="number"
            value={row['failedLoginAttempts'] ?? ''}
            onChange={(e) => store.setValue('failedLoginAttempts', e.target.value === '' ? null : Number(e.target.value) as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="ipAddress" className="text-xs font-semibold text-slate-400">
            Ip Address
          </label>
          <input
            id="ipAddress"
            type="text"
            value={row['ipAddress'] ?? ''}
            onChange={(e) => store.setValue('ipAddress', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastFailedLogin" className="text-xs font-semibold text-slate-400">
            Last Failed Login
          </label>
          <input
            id="lastFailedLogin"
            type="datetime-local"
            value={row['lastFailedLogin'] ? String(row['lastFailedLogin']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('lastFailedLogin', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastFailedLoginIpAddress" className="text-xs font-semibold text-slate-400">
            Last Failed Login Ip Address
          </label>
          <input
            id="lastFailedLoginIpAddress"
            type="text"
            value={row['lastFailedLoginIpAddress'] ?? ''}
            onChange={(e) => store.setValue('lastFailedLoginIpAddress', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastLogin" className="text-xs font-semibold text-slate-400">
            Last Login
          </label>
          <input
            id="lastLogin"
            type="datetime-local"
            value={row['lastLogin'] ? String(row['lastLogin']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('lastLogin', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastPasswordReset" className="text-xs font-semibold text-slate-400">
            Last Password Reset
          </label>
          <input
            id="lastPasswordReset"
            type="datetime-local"
            value={row['lastPasswordReset'] ? String(row['lastPasswordReset']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('lastPasswordReset', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastPasswordResetBy" className="text-xs font-semibold text-slate-400">
            Last Password Reset By
          </label>
          <input
            id="lastPasswordResetBy"
            type="text"
            value={row['lastPasswordResetBy'] ?? ''}
            onChange={(e) => store.setValue('lastPasswordResetBy', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="lastPasswordResetIpAddress" className="text-xs font-semibold text-slate-400">
            Last Password Reset Ip Address
          </label>
          <input
            id="lastPasswordResetIpAddress"
            type="text"
            value={row['lastPasswordResetIpAddress'] ?? ''}
            onChange={(e) => store.setValue('lastPasswordResetIpAddress', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="locationName" className="text-xs font-semibold text-slate-400">
            Location Name
          </label>
          <input
            id="locationName"
            type="text"
            value={row['locationName'] ?? ''}
            onChange={(e) => store.setValue('locationName', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={128}
          />
        </div>
        <div className="flex items-center gap-2 py-2">
          <input
            id="locked"
            type="checkbox"
            checked={!!(row['locked'] ?? false)}
            onChange={(e) => store.setValue('locked', e.target.checked as any, rowId)}
            className="h-4 w-4 rounded border-slate-700 bg-slate-800 text-indigo-600 focus:ring-indigo-500"
          />
          <label htmlFor="locked" className="text-sm font-medium text-slate-300">
            Locked
          </label>
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="passwordHash" className="text-xs font-semibold text-slate-400">
            Password Hash *
          </label>
          <input
            id="passwordHash"
            type="text"
            value={row['passwordHash'] ?? ''}
            onChange={(e) => store.setValue('passwordHash', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
            maxLength={256}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="picture" className="text-xs font-semibold text-slate-400">
            Picture
          </label>
          <input
            id="picture"
            type="text"
            value={row['picture'] ?? ''}
            onChange={(e) => store.setValue('picture', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
            maxLength={undefined}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="previousPasswordHashes" className="text-xs font-semibold text-slate-400">
            Previous Password Hashes (JSON)
          </label>
          <textarea
            id="previousPasswordHashes"
            rows={3}
            value={typeof row['previousPasswordHashes'] === 'object' ? JSON.stringify(row['previousPasswordHashes'], null, 2) : row['previousPasswordHashes'] ?? ''}
            onChange={(e) => {
              try {
                const val = e.target.value === '' ? null : JSON.parse(e.target.value);
                store.setValue('previousPasswordHashes', val, rowId);
              } catch {
                store.setValue('previousPasswordHashes', e.target.value as any, rowId);
              }
            }}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-mono text-slate-200 focus:border-indigo-500 focus:outline-none"
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="settings" className="text-xs font-semibold text-slate-400">
            Settings (JSON)
          </label>
          <textarea
            id="settings"
            rows={3}
            value={typeof row['settings'] === 'object' ? JSON.stringify(row['settings'], null, 2) : row['settings'] ?? ''}
            onChange={(e) => {
              try {
                const val = e.target.value === '' ? null : JSON.parse(e.target.value);
                store.setValue('settings', val, rowId);
              } catch {
                store.setValue('settings', e.target.value as any, rowId);
              }
            }}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-mono text-slate-200 focus:border-indigo-500 focus:outline-none"
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="startDate" className="text-xs font-semibold text-slate-400">
            Start Date *
          </label>
          <input
            id="startDate"
            type="datetime-local"
            value={row['startDate'] ? String(row['startDate']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('startDate', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="updatedAt" className="text-xs font-semibold text-slate-400">
            Updated At *
          </label>
          <input
            id="updatedAt"
            type="datetime-local"
            value={row['updatedAt'] ? String(row['updatedAt']).substring(0, 16) : ''}
            onChange={(e) => store.setValue('updatedAt', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="updatedBy" className="text-xs font-semibold text-slate-400">
            Updated By *
          </label>
          <input
            id="updatedBy"
            type="text"
            value={row['updatedBy'] ?? ''}
            onChange={(e) => store.setValue('updatedBy', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
            maxLength={128}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="userId" className="text-xs font-semibold text-slate-400">
            User Id
          </label>
          <input
            id="userId"
            type="number"
            value={row['userId'] ?? ''}
            onChange={(e) => store.setValue('userId', e.target.value === '' ? null : Number(e.target.value) as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={false}
          />
        </div>
        <div className="flex flex-col gap-1">
          <label htmlFor="userName" className="text-xs font-semibold text-slate-400">
            User Name *
          </label>
          <input
            id="userName"
            type="text"
            value={row['userName'] ?? ''}
            onChange={(e) => store.setValue('userName', e.target.value === '' ? null : e.target.value as any, rowId)}
            className="w-full rounded border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 focus:border-indigo-500 focus:outline-none"
            required={true}
            maxLength={128}
          />
        </div>
      </div>
    </div>
  );
}
