/* Generated by uv-core codegen */

'use client';

import { HeaderCell, DataTableCell } from '@/components/core/table';
import { useClientSession } from '@/components/core/session-context';
import { createActionsColumn, type TableAction } from '@/components/core/table/actions-column-def';
import { Pencil } from 'lucide-react';
import type { UVRoles } from '@/lib/common/ds/types/app/UVRoles.js';
import type { Store } from 'uv-core/client';
import type { AccessorKeyColumnDef } from '@tanstack/react-table';
import { useMemo } from 'react';

export default function useUVRolesTableColumns(
  store: Store<UVRoles>,
): AccessorKeyColumnDef<UVRoles>[] {
  const session = useClientSession();
  const roles = session?.roles;
  return useMemo(() => {
    if (!roles) {
      return [];
    }
    const columns: AccessorKeyColumnDef<UVRoles>[] = [
      {
        accessorKey: 'appId',
        meta: {
          label: 'App Id',
        },
        size: 200,
        header: (props) => {
          return <HeaderCell {...props} type="Text" store={store} accessorKey="appId" title="App Id" />;
        },
        cell: (props) => <DataTableCell type="Text" attributeCode="appId" {...props} />,
      },
      {
        accessorKey: 'description',
        meta: {
          label: 'Description',
        },
        size: 200,
        header: (props) => {
          return <HeaderCell {...props} type="Text" store={store} accessorKey="description" title="Description" />;
        },
        cell: (props) => <DataTableCell type="Text" attributeCode="description" {...props} />,
      },
      {
        accessorKey: 'endDate',
        meta: {
          label: 'End Date',
        },
        size: 110,
        header: (props) => {
          return <HeaderCell {...props} type="Date" store={store} accessorKey="endDate" title="End Date" />;
        },
        cell: (props) => <DataTableCell type="Date" attributeCode="endDate" {...props} />,
      },
      {
        accessorKey: 'roleCode',
        meta: {
          label: 'Role Code',
        },
        size: 200,
        header: (props) => {
          return <HeaderCell {...props} type="Text" store={store} accessorKey="roleCode" title="Role Code" />;
        },
        cell: (props) => <DataTableCell type="Text" attributeCode="roleCode" {...props} />,
      },
      {
        accessorKey: 'roleName',
        meta: {
          label: 'Role Name',
        },
        size: 200,
        header: (props) => {
          return <HeaderCell {...props} type="Text" store={store} accessorKey="roleName" title="Role Name" />;
        },
        cell: (props) => <DataTableCell type="Text" attributeCode="roleName" {...props} />,
      },
      {
        accessorKey: 'startDate',
        meta: {
          label: 'Start Date',
        },
        size: 110,
        header: (props) => {
          return <HeaderCell {...props} type="Date" store={store} accessorKey="startDate" title="Start Date" />;
        },
        cell: (props) => <DataTableCell type="Date" attributeCode="startDate" {...props} />,
      },
      createActionsColumn(
        [
          {
            label: 'Edit',
            icon: <Pencil className="size-4" />,
            onClick: ({ rowId, table }) => {
              table.options.meta?.onEdit?.(rowId);
            },
          },
        ],
        { size: 80, title: 'Actions' },
      ),
    ];
    return columns;
  }, [roles, store]);
}
