/* Generated by uv-core codegen */

'use client';

import type { UVRoles } from '@/lib/common/ds/types/app/UVRoles.js';
import { useStore } from 'uv-core/client';

export function useUVRolesStore() {
  return useStore<UVRoles>({
    datasourceId: 'UVRoles',
    page: 'uvroles-page',
    alias: 'uvroles-all',
    limit: 20,
    includeCount: true,
    autoQuery: true,
    // onInitialized: async (store) => {
    //   store.setIsLoading(false);
    // },
  });
}
