/* Generated by uv-core codegen */

import type { ISODateTimeString } from 'uv-core';

export interface UVRoles {
  appId: string;
  createdAt: ISODateTimeString;
  createdBy: string;
  description?: string | null;
  endDate?: ISODateTimeString | null;
  roleCode: string;
  roleName: string;
  startDate: ISODateTimeString;
  updatedAt: ISODateTimeString;
  updatedBy: string;
}
