/* Generated by uv-core codegen */

export interface UVUsers {
  apiKey?: string | null;
  apiSecret?: string | null;
  createdAt: string;
  createdBy: string;
  displayName: string;
  email: string;
  endDate?: string | null;
  failedLoginAttempts: number;
  ipAddress?: string | null;
  lastFailedLogin?: string | null;
  lastFailedLoginIpAddress?: string | null;
  lastLogin?: string | null;
  lastPasswordReset?: string | null;
  lastPasswordResetBy?: string | null;
  lastPasswordResetIpAddress?: string | null;
  locationName?: string | null;
  locked: boolean;
  passwordHash: string;
  picture?: string | null;
  previousPasswordHashes: any;
  settings: any;
  startDate: string;
  updatedAt: string;
  updatedBy: string;
  userId?: number | null;
  userName: string;
}
