/* Generated by uv-core codegen */

'use client';

import { HeaderCell, DataTableCell } from '@/components/core/table';
import { useClientSession } from '@/components/core/session-context';
import { createActionsColumn } from '@/components/core/table/actions-column-def';
import { Pencil } from 'lucide-react';
import type { UVUsers } from '@/lib/common/ds/types/app/UVUsers.js';
import type { Store } from 'uv-core/client';
import type { AccessorKeyColumnDef } from '@tanstack/react-table';
import { useMemo } from 'react';

export default function useUVUsersTableColumns(
  store: Store<UVUsers>,
): AccessorKeyColumnDef<UVUsers>[] {
  const session = useClientSession();
  const roles = session?.roles;
  return useMemo(() => {
    if (!roles) {
      return [];
    }
    const columns: AccessorKeyColumnDef<UVUsers>[] = [
      {
        accessorKey: 'apiKey',
        meta: { label: 'Api Key' },
        size: 200,
        header: (props) => <HeaderCell {...props} type="Text" store={store} accessorKey="apiKey" title="Api Key" />,
        cell: (props) => <DataTableCell type="Text" attributeCode="apiKey" {...props} />,
      },
      {
        accessorKey: 'displayName',
        meta: { label: 'Display Name' },
        size: 200,
        header: (props) => <HeaderCell {...props} type="Text" store={store} accessorKey="displayName" title="Display Name" />,
        cell: (props) => <DataTableCell type="Text" attributeCode="displayName" {...props} />,
      },
      {
        accessorKey: 'email',
        meta: { label: 'Email' },
        size: 200,
        header: (props) => <HeaderCell {...props} type="Text" store={store} accessorKey="email" title="Email" />,
        cell: (props) => <DataTableCell type="Text" attributeCode="email" {...props} />,
      },
      {
        accessorKey: 'startDate',
        meta: { label: 'Start Date' },
        size: 110,
        header: (props) => <HeaderCell {...props} type="Date" store={store} accessorKey="startDate" title="Start Date" />,
        cell: (props) => <DataTableCell type="Date" attributeCode="startDate" {...props} />,
      },
      {
        accessorKey: 'endDate',
        meta: { label: 'End Date' },
        size: 110,
        header: (props) => <HeaderCell {...props} type="Date" store={store} accessorKey="endDate" title="End Date" />,
        cell: (props) => <DataTableCell type="Date" attributeCode="endDate" {...props} />,
      },
      {
        accessorKey: 'locked',
        meta: { label: 'Locked' },
        size: 90,
        header: (props) => <HeaderCell {...props} type="Boolean" store={store} accessorKey="locked" title="Locked" />,
        cell: (props) => <DataTableCell type="Boolean" attributeCode="locked" {...props} />,
      },
      {
        accessorKey: 'failedLoginAttempts',
        meta: { label: 'Failed Login Attempts' },
        size: 90,
        header: (props) => <HeaderCell {...props} type="Number" store={store} accessorKey="failedLoginAttempts" title="Failed Login Attempts" />,
        cell: (props) => <DataTableCell type="Number" attributeCode="failedLoginAttempts" {...props} />,
      },
      {
        accessorKey: 'lastLogin',
        meta: { label: 'Last Login' },
        size: 110,
        header: (props) => <HeaderCell {...props} type="Date" store={store} accessorKey="lastLogin" title="Last Login" />,
        cell: (props) => <DataTableCell type="Date" attributeCode="lastLogin" {...props} />,
      },
      {
        accessorKey: 'userName',
        meta: { label: 'User Name' },
        size: 200,
        header: (props) => <HeaderCell {...props} type="Text" store={store} accessorKey="userName" title="User Name" />,
        cell: (props) => <DataTableCell type="Text" attributeCode="userName" {...props} />,
      },
      {
        accessorKey: 'locationName',
        meta: { label: 'Location Name' },
        size: 200,
        header: (props) => <HeaderCell {...props} type="Text" store={store} accessorKey="locationName" title="Location Name" />,
        cell: (props) => <DataTableCell type="Text" attributeCode="locationName" {...props} />,
      },
      createActionsColumn(
        [
          {
            label: 'Edit',
            icon: <Pencil className="size-4" />,
            onClick: ({ rowId, table }) => {
              table.options.meta?.onEdit?.(rowId);
            },
          },
        ],
        { size: 80, title: 'Actions' },
      ),
    ];
    return columns;
  }, [roles, store]);
}
