/* Generated by uv-core codegen */

'use client';

import type { UVUsers } from '../../../../lib/common/ds/types/app/UVUsers.js';
import { useStore } from 'uv-core/client';

export function useUVUsersStore() {
  return useStore<UVUsers>({
    datasourceId: 'UVUsers',
    alias: 'uv-users-all',
    autoQuery: true,
  });
}
