/* Generated by uv-core codegen */

'use client';

import { PageLayoutTemplate } from '@/components/core/page';
import { Users } from 'lucide-react';
import UVUsersEditForm from './components/edit-form';
import useUVUsersSmartSearchColumns from './hooks/smart-search-columns';
import useUVUsersTableColumns from './hooks/table-columns';
import { useUVUsersStore } from './hooks/use-store';

export default function UVUsersPageContent() {
  const store = useUVUsersStore();
  const smartSearchColumns = useUVUsersSmartSearchColumns();
  const tableColumns = useUVUsersTableColumns(store);

  return (
    <PageLayoutTemplate
      title="UV Users"
      subTitle="Manage UV Users"
      icon={<Users className="h-12 w-12 text-muted-foreground" />}
      store={store}
      smartSearchColumns={smartSearchColumns}
      tableColumns={tableColumns}
      pageId="uv-users-page"
      itemId="uv-users"
      editForm={<UVUsersEditForm store={store} />}
      getDefaultRow={() => {
        return {};
      }}
      addNewButtonText="Add New UV User"
    />
  );
}
